version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=psw
    ports:
      - 15672:15672

  pub:
    build: ./pub
    depends_on:
      - rabbitmq
  sub:
    build: ./sub
    depends_on:
      - rabbitmq